# docker-compose.yml
version: '3.1'
services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: dockerfile
    container_name: "prometheus"
    hostname: "prometheus"
    ports:
      - "9090:9090"
    links:    
      - mvcapp

  grafana:
    image: grafana/grafana
    container_name: "grafana"
    hostname: "grafana"
    ports:
      - "3000:3000"
    links:
      - prometheus
      
  alertmanager:
    build:
      context: ./alertmanager
      dockerfile: dockerfile
    container_name: "alert-manager"
    hostname: "alert-manager"
    command:
      - '--config.file=/etc/prometheus/alertmanager.yml'
    ports:
      - '9093:9093'
    links:    
      - prometheus
  
  mvcapp:
      container_name: "mvcapp"
      hostname: "mvcapp"
      image: erakm5493/devops:latest
      ports:
        - "80:80"
      environment:
        ConnectionStrings__ProductsContext: "Server=db;Database=ProductsContext;User=sa;Password=@Aa123456;"
      depends_on:
              - db

  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
         SA_PASSWORD: "@Aa123456"
         ACCEPT_EULA: "Y"
      
